// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * bench_zvram - throughput/latency benchmark for VRAM-backed (or RAM-backed)
 * zswap.  Each worker thread fills a private anonymous buffer, pushes it to
 * swap with MADV_PAGEOUT (store path: compress -> VRAM), then touches every
 * page to fault it back in (load path: VRAM -> decompress) -- timing each
 * phase.  Run with zswap.vram_backed=0 and =1 to compare.
 *
 * Store and load run as separate parallel phases so the harness can read
 * pswpout/pswpin from /proc/vmstat around each and report how many pages were
 * *actually* moved -- a load that touches resident (un-evicted) pages is a
 * measurement artifact, not a real swap-in.
 *
 * Data is generated by a per-page xorshift keystream so it is (a) tunably
 * (in)compressible and (b) verifiable, so the benchmark doubles as a stress
 * test.  MADV_PAGEOUT (Linux 5.4+) needs an active swap device.
 *
 * Build: cc -O2 -pthread -o bench_zvram bench_zvram.c
 * Run:   sudo ./bench_zvram -t 8 -m 256 -i 3
 */
#define _GNU_SOURCE
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
#include <sys/mman.h>
#include <fcntl.h>

#define PAGE 4096UL

static unsigned long per_thread_bytes = 256UL << 20;	/* -m MiB per thread */
static int nthreads = 4;				/* -t */
static int iters = 3;					/* -i */
static int compress_pct = 0;	/* -c: % of each page that is zero (compressible) */

static double now_s(void)
{
	struct timespec ts;
	clock_gettime(CLOCK_MONOTONIC, &ts);
	return ts.tv_sec + ts.tv_nsec / 1e9;
}

/* Read a single counter from /proc/vmstat (e.g. "pswpin", "pswpout"). */
static unsigned long vmstat(const char *key)
{
	char line[128];
	unsigned long v = 0;
	size_t klen = strlen(key);
	FILE *f = fopen("/proc/vmstat", "r");

	if (!f)
		return 0;
	while (fgets(line, sizeof(line), f)) {
		if (!strncmp(line, key, klen) && line[klen] == ' ') {
			v = strtoul(line + klen + 1, NULL, 10);
			break;
		}
	}
	fclose(f);
	return v;
}

/* Deterministic, verifiable page fill. The first @zero_bytes are zero (free
 * compression); the rest is an xorshift64 keystream seeded by the offset. */
static void fill_page(unsigned char *p, unsigned long seed, unsigned long zero_bytes)
{
	uint64_t x = seed ? seed : 0x9e3779b97f4a7c15ULL;
	unsigned long i;

	memset(p, 0, zero_bytes);
	for (i = zero_bytes; i < PAGE; i += 8) {
		x ^= x << 13; x ^= x >> 7; x ^= x << 17;
		memcpy(p + i, &x, 8);
	}
}

struct work {
	int id;
	unsigned char *buf;
	double store_s, load_s;
	long bad;
};

/* Phase 1: fill the buffer, then evict it to swap -> zswap -> (VRAM). */
static void *phase_store(void *arg)
{
	struct work *w = arg;
	unsigned long n = per_thread_bytes, off;
	unsigned long zero_bytes = (PAGE * compress_pct) / 100;
	double t0;

	for (off = 0; off < n; off += PAGE)
		fill_page(w->buf + off, off + 1, zero_bytes);

	t0 = now_s();
	if (madvise(w->buf, n, MADV_PAGEOUT))
		fprintf(stderr, "t%d: MADV_PAGEOUT: %s\n", w->id, strerror(errno));
	w->store_s = now_s() - t0;
	return NULL;
}

/* Phase 2: touch one byte per page (timed swap-in), then verify (untimed). */
static void *phase_load(void *arg)
{
	struct work *w = arg;
	unsigned long n = per_thread_bytes, off;
	unsigned long zero_bytes = (PAGE * compress_pct) / 100;
	volatile unsigned char sink = 0;
	double t0;

	t0 = now_s();
	for (off = 0; off < n; off += PAGE)
		sink ^= w->buf[off];
	w->load_s = now_s() - t0;
	(void)sink;

	unsigned char tmp[PAGE];
	for (off = 0; off < n; off += PAGE) {
		fill_page(tmp, off + 1, zero_bytes);
		if (memcmp(w->buf + off, tmp, PAGE))
			w->bad++;
	}
	return NULL;
}

static double run_phase(void *(*fn)(void *), struct work *w, pthread_t *th)
{
	int i;
	double t0 = now_s();

	for (i = 0; i < nthreads; i++)
		pthread_create(&th[i], NULL, fn, &w[i]);
	for (i = 0; i < nthreads; i++)
		pthread_join(th[i], NULL);
	return now_s() - t0;
}

/*
 * Flush dirty data and drop clean page cache so the load phase reads cold.
 * Without this, a swapfile's blocks stay cached in RAM after the store phase
 * and the "disk" swap-in is served from page cache, not the device.  zswap
 * backends keep compressed data in their own pool (VRAM/RAM), not page cache,
 * so this only affects the disk-swap case -- making the comparison honest.
 * Needs root.
 */
static void drop_caches(void)
{
	int fd;

	sync();
	fd = open("/proc/sys/vm/drop_caches", O_WRONLY);
	if (fd < 0) {
		perror("drop_caches (-d needs root)");
		return;
	}
	if (write(fd, "3\n", 2) < 0)
		perror("write drop_caches");
	close(fd);
}

int main(int argc, char **argv)
{
	int c, i, it, drop = 0;

	while ((c = getopt(argc, argv, "t:m:i:c:d")) != -1) {
		switch (c) {
		case 't': nthreads = atoi(optarg); break;
		case 'm': per_thread_bytes = strtoul(optarg, NULL, 0) << 20; break;
		case 'i': iters = atoi(optarg); break;
		case 'c': compress_pct = atoi(optarg); break;
		case 'd': drop = 1; break;
		default:
			fprintf(stderr, "usage: %s [-t threads] [-m MiB/thread] "
				"[-i iters] [-c zero%%] [-d drop caches]\n", argv[0]);
			return 2;
		}
	}

	struct work *w = calloc(nthreads, sizeof(*w));
	pthread_t *th = calloc(nthreads, sizeof(*th));

	for (i = 0; i < nthreads; i++) {
		w[i].id = i;
		w[i].buf = mmap(NULL, per_thread_bytes, PROT_READ | PROT_WRITE,
				MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
		if (w[i].buf == MAP_FAILED) {
			perror("mmap");
			return 1;
		}
	}

	unsigned long pages = per_thread_bytes / PAGE * nthreads;
	double tot_gb = (double)per_thread_bytes * nthreads / (1UL << 30);
	printf("threads=%d  per-thread=%lu MiB  total=%.2f GiB  zero%%=%d  pages=%lu\n",
	       nthreads, per_thread_bytes >> 20, tot_gb, compress_pct, pages);

	for (it = 0; it < iters; it++) {
		unsigned long zo0 = vmstat("zswpout"), po0 = vmstat("pswpout");
		double store = run_phase(phase_store, w, th);
		unsigned long zswpout = vmstat("zswpout") - zo0;
		unsigned long spill = vmstat("pswpout") - po0;	/* hit disk */

		if (drop)
			drop_caches();

		unsigned long zi0 = vmstat("zswpin"), pi0 = vmstat("pswpin");
		double load = run_phase(phase_load, w, th);
		unsigned long zswpin = vmstat("zswpin") - zi0;
		unsigned long diskin = vmstat("pswpin") - pi0;	/* real device reads */

		long bad = 0;
		for (i = 0; i < nthreads; i++)
			bad += w[i].bad;

		printf("iter %d: store %6.0f MiB/s (%5.0f ns/pg, zswpout %lu spill %lu) | "
		       "load %6.0f MiB/s (%5.0f ns/pg, zswpin %lu diskin %lu) /%lu | bad=%ld\n",
		       it,
		       tot_gb * 1024 / store, store * 1e9 / pages, zswpout, spill,
		       tot_gb * 1024 / load,  load  * 1e9 / pages, zswpin, diskin, pages,
		       bad);
	}
	return 0;
}
